"""empty message
Revision ID: 923d5791b9f6
Revises: 53719df12f9e
Create Date: 2022-03-01 18:30:40.534362
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923d5791b9f6'
down_revision = '53719df12f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user_profiles', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
